/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_test_jni_ParamerExampleJNI */

#ifndef _Included_com_test_jni_ParamerExampleJNI
#define _Included_com_test_jni_ParamerExampleJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_test_jni_ParamerExampleJNI
 * Method:    sum
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_com_test_jni_ParamerExampleJNI_sum
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_test_jni_ParamerExampleJNI
 * Method:    sayHello
 * Signature: (Ljava/lang/String;Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_test_jni_ParamerExampleJNI_sayHello
  (JNIEnv *, jobject, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
